# Generated by Django 4.0.6 on 2022-08-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='borrowed_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
