# Generated by Django 4.0.6 on 2022-08-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_bookinstance_borrowed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
